[project]
name = "lambdalib"
version = "0.1.0"
description = "Lambdalib library of different core and toold for amaranth"
authors = [
    {name = "PO Vauboin", email = "po@lambdaconcept.com"},
    {name = "Pierre-Olivier Vauboin", email = "po@lambdaconcept.com"},
]
dependencies = [
    "setuptools>=69.0.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
"Source Code" = "https://github.com/lambdaconcept/lambdalib"
"Bug Tracker" = "https://github.com/lambdaconcept/lambdalib/issues"
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

